version: 0.2

phases:
  install:
    commands:
      - echo installing nodejs...
      - curl -sL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs  #aws code build use ubuntu environement
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ng build --prod
  post_build:
    commands:
      - mv appspec.yml ./dist/angular-application
      - mv scripts ./dist/angular-application
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/angular-application
